version: "2"
services:
  ajaxcrud:
    build: ./
    labels:
      - "traefik.backend=ajaxcrud"
  #    - "traefik.frontend.rule=Host:ajaxcrud.docker.localhost"
    environment:
      - MYSQL_HOST=mysql
      - APACHE_SERVER_NAME=ajaxcrud.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_XDEBUG_ENABLED=true
    networks:
      - default
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    # ADD in permission for setting system time to host system time
    cap_add:
      - SYS_TIME
      - SYS_NICE

  database:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

#networks:
#  default:
#    external:
#      name: docker_docker-localhost
